### ISSUE TITLE
clustering.cluster() output

### ISSUE THREAD

**Issue by cjhopp** [calum-chamberlain/EQcorrscan#19]
The variable 'groups' is not populated correctly at the end of clustering.cluster():

At line 181 - end of function: Inner loop not allowed to run through all indeces due to 'break'

The following works as ln 181 to EOFunction:

    for group_id in group_ids:
        group=[]
        for ind in indeces:
            if ind[0] == group_id:
                group.append(stream_list[ind[1]])
        groups.append(group)
    return groups

**Comment by calum-chamberlain** [comment]
Should be fixed [here](https://github.com/calum-chamberlain/EQcorrscan/commit/7c83b3038d53be743bb8eef7a511653e620bede7)

Change break condition from else to elif ind[0] > group_id
