### ISSUE TITLE
pre_processing.shortproc()

### ISSUE THREAD

**Issue by cjhopp** [calum-chamberlain/EQcorrscan#20]
shortproc() only accepts traces with 3 letter channel names. Processing  throws a 'string index out of range' error for channels which are already 2 characters long.

Issue arose when I was processing some templates I had already created using clustering.emiprical_SVD() which outputs traces with 2-character channel names (I think).

Line 94:

        tr.stats.channel=tr.stats.channel[0]+tr.stats.channel[2]

**Comment by calum-chamberlain** [comment]
Patched [here](https://github.com/calum-chamberlain/EQcorrscan/commit/a3b683160e4ded6ff0fef3e4a636ba22b443a423)
Issue also patched in long-proc.  I also removed unnecessary channel renaming for conditions specific to my old SAC data.
