### ISSUE TITLE
four letter station names

### ISSUE THREAD

**Issue by xiansch** [calum-chamberlain/EQcorrscan#29]
I'm having some trouble with four letter station names, and I'm not sure if it is caused by writing to mseed.  When the templates are cut (template_gen) the output will say "Cutting N.IWEH.UU"
But performing the match_filter part will show 
I have template info for these stations:
[u'N.IWE.NN', u'N.IWE.EE', u'N.IWE.UU']
I have daylong data for these stations:
[u'N.IWEH.UU', u'N.IWEH.EE', u'N.IWEH.NN']
so as you can see the last letter of the station has gotten cut.  This leads to some problems with the checks in place to make sure that the stations correspond so the match_filter doesn't work properly.  I've done a quick and dirty fix by simply appending +"H" to match_filter.match_filter
if debug >= 2:
        print('Ensuring all template channels have matches in daylong data')
    template_stachan = []
    for template in templates:
        for tr in template:
            template_stachan += [(tr.stats.station+"H", tr.stats.channel)]
    template_stachan = list(set(template_stachan))

but I'm not sure if this is causing problems any where else.  When running without compile errors I run the template over the day long dataset from which it was cut and I get 
********* DEBUG:  N.IWEH.UU ccc MAX: 0.0
********* DEBUG:  N.IWEH.UU ccc MAX: 0.0
********* DEBUG:  N.IWEH.UU ccc MEAN: 0.0
********* DEBUG:  N.IWEH.UU ccc MEAN: 0.0
********* DEBUG:  N.IWEH.UU ccc MAX: 0.0
shape of ccc: (1, 1726401)
A single ccc is using: 3.452802MB
with zero detections, but I'm not sure if this is related to the naming issue or not.

**Comment by calum-chamberlain** [comment]
This stems strange. How are you writing the templates to miniseed? 

The next thing is the zero maximums of the cross-correlations, that would usually only occur when there is no matching data. How many templates are you using? Bear in mind that one template should represent one event, not just one channel.
That you only have zeros in the correlation would explain why you have no detections though.

Adding the h to the match filter is not the correct work around, there are deeper checks that again look at the trace headers. If the station is somehow named incorrectly then you should edit the trace headers themselves outside of the functions. E.g. before running match_filter.match_filter, you could do edit the tr.stats.station. it's not clear to me how this has lost the last letter though, the template generation shouldn't do this.

**Comment by xiansch** [comment]
I'm using template.write(filename, format='MSEED').
I think this is the cause of the dropped letter, since I tried also writing the daylong sac files to mseed and read them back and the same thing happened, so I solved the problem by reading all of the continuous data also as minseed and then read back.  The last letter H is common to all station names so not really important.
I am just using one template now, before I had 3 of them because like in the EQcorrscan tutorial I wrote 
for i, template in enumerate(templates)
templates.write() etc,
but this would write the 3 components to different templates since I only actually have one event, so I just removed the for loop, probably put it back in when using more templates.  So now I am able to find the peak, thanks.

**Comment by calum-chamberlain** [comment]
Okay, that is odd that obspy is doing that, can you tell me what obspy version you are using? I can try and investigate and maybe we can work on it in obspy.

Also, the point of the list given to template_gen.from_sac is that you can give all traces associated with the event. It will then make a multi channel template, which can be stored in multiplexed miniseed. I will make this explicit on the docs in the next version, and write an example in there too. Glad things are working!

**Comment by xiansch** [comment]
I'm using obspy 1.0.0.
Just a quick question, does from_sac/obspy read only the T0, T1, ...T9 picks?
I think there is also an "A" pick but this is not being picked up by the program.
Thanks.

**Comment by calum-chamberlain** [comment]
It might be worth upgrading to the newly released obspy 1.0.1, they added some sac patches there.

As for picks, yes, it currently only read from t0-9, I'm not a sac user, so I'm not totally familiar with what picks are stored where, in what instance would you use a rather than t0-9? 

It should be a simple fix in utils.sac_utils. I can add it in this afternoon?

**Comment by xiansch** [comment]
There is also "A".
A	(float)	First arrival time (seconds relative to reference time.)
KA	(marker)	First arrival time identification.

**Comment by calum-chamberlain** [comment]
Okay, shall add. Had glossed over these because the sac files I had didn't use them. If you need the patch sooner you can add in to sac_util.

**Comment by calum-chamberlain** [comment]
Added, and pushed, and changed the positions of picks in the test data to ensure that picks from header values a and t[0-9] are included.

Let me know if there are any issues!

Thanks for finding these things, from_sac is in the early days and I haven't programmed all the functionality possible into sac_util...
