### ISSUE TITLE
detection_multiplot

### ISSUE THREAD

**Issue by xiansch** [calum-chamberlain/EQcorrscan#30]
I tried plotting the detections with detection_multiplot and saving in pdf format.  There appears to be a row of 0's printed over the times on the x axis so that they are illegible (see attached) and I am not sure what could be causing that.
[dete	ction_2012-04-02T11:49:48.250000Z.pdf](https://github.com/calum-chamberlain/EQcorrscan/files/218131/dete.ction_2012-04-02T11.49.48.250000Z.pdf)

Also, would it be possible to plot the templates and data with some vertical space between them so that the template doesn't block out the data waveform?
Thanks

**Comment by calum-chamberlain** [comment]
This is because I haven't tried using templates that long, so the x-axis is labelled to seconds, I can rotate the axis labels - I'll have a play later.

I am curious as to why you are using such long templates?  Do you think there is useful information in all of the coda?

You could certainly offset the template vertically by adding some constant to the template data, I can add this as an option.

**Comment by xiansch** [comment]
Hmm that is a good point, I could certainly reduce the amount of noise detected by clipping off the coda.  The long templates were originally chosen because some of the intermediate depth earthquakes were quite far from the stations so the actual waveforms were quite long, with a large gap between P and S arrival.
But it might be a better idea to match the vertical components to the a window around the P arrival and the horizontal components to a window around the S arrival and give some leeway for the earthquake distance/depth.

**Comment by calum-chamberlain** [comment]
That (using P on the vertical and S on the horizontal) is what I usually do, and it looks like what you have done in the figure.  Generally you get higher correlation values with shorter waveforms as there is less noise...
EQcorrscan.core.match_filter takes care of all (hopefully) the lagging and alignment problems that could come from having large and very variable source - receiver distances.
As an aside, I don't usually use templates longer than 6s.  For local micro-earthquakes with impulsive arrivals I would usually use shorter, 1-3s templates.  Plans are afoot to conduct a detailed study into how template variations affect the detections, but that will be a long time away.
