### ISSUE TITLE
eqcorrscan.utils.clustering.group_delays

### ISSUE THREAD

**Issue by blazvicic** [calum-chamberlain/EQcorrscan#42]
Hi.

I tried running group_delays

```
from obspy import read
import glob
import os
from eqcorrscan.utils.clustering import group_delays

path = '/home/blaz/Documents/eqcorrscan/Postojna/template'
stream_files = glob.glob(os.path.join(path, '*'))
stream_list = [(read(stream_file), i)
               for i, stream_file in enumerate(stream_files) ]

groups = group_delays(stream_list=stream_list)

```

the error I get is:

> Working on waveform 0 0f 85
> Traceback (most recent call last):
>   File "group_delays.py", line 17, in <module>
>     groups = group_delays(stream_list=stream_list)
>   File "/home/blaz/anaconda2/lib/python2.7/site-packages/EQcorrscan-0.103rc0-py2.7egg/eqcorrscan/utils/clustering.py", line 227, in group_delays
>     starttimes.append(tr.stats.starttime)
> AttributeError: 'Stream' object has no attribute 'stats'

So, basicly it treats my stream_list as a stream_list, not traces (as I understand from source), hence no attribute 'stats' is found. 

i checked if there is something wrong with my templates so i run that:

```
from obspy import read
import glob
import os
from eqcorrscan.utils.clustering import group_delays

path = '/home/blaz/Documents/eqcorrscan/Postojna/template'
stream_files = glob.glob(os.path.join(path, '*'))
stream_list = [(read(stream_file), i)
               for i, stream_file in enumerate(stream_files) ]
for stream in stream_list:
  for tr in stream[0]:
    print tr.stats.starttime
#groups = group_delays(stream_list=stream_list)

```
it prints starttimes of traces without problems, so my templates are OK, i guess.

Thanks for the help,
Blaz

**Comment by calum-chamberlain** [comment]
You provided a list of tuples of (obspy.core.stream.Stream, int) by generating your stream_list with that i in there.
